### ISSUE TITLE
Grinding with a bone mortar and pestle yields no reagents, ever.

### ISSUE THREAD

**Issue by MarinaGryphon** [judgex/desertrose#202]
Issue reported from  Round ID: 1073 (Desert Rose 2)

Reporting client version: 512

When grinding agave leaf or similar plants with a mortar, no result is produced.

**Comment by Laus4Deus** [comment]
Thank you for taking the time of using your github account to pin this issue here.

It's an issue that has been communicated plenty of times in the discord, but the problem is that the grinder code and the mostar & pestle code are way too different. It seems whoever built the code of the later made it so only things that have `grind_results` work propperly.

Wheat & Oat both have the following, as an example.
`grind_results = list("flour" = 0)`

And produce flour when grinded.

Currently we code in our free time what catches our interest and this issue is not as appealing as the large updates the good coders have been pumping. And I assure you, fixing this bug would be just as time consuming
